#!/bin/bash
# SPF Flattener Installation Script
# 
# This script will:
# 1. Create the MySQL database and tables
# 2. Set up directory permissions
# 3. Generate a sample configuration file
# 4. Optionally set up the cron job

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "======================================"
echo "  SPF Flattener Installation Script"
echo "======================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check PHP is installed
if ! command -v php &> /dev/null; then
    echo -e "${RED}Error: PHP is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}✓ PHP found:$(php -v | head -n1)${NC}"

# Check MySQL/MariaDB
if ! command -v mysql &> /dev/null; then
    echo -e "${RED}Error: MySQL client is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}✓ MySQL client found${NC}"
echo ""

# Database setup
echo "=== Database Configuration ==="
read -p "MySQL root username [root]: " DB_USER
DB_USER=${DB_USER:-root}
read -sp "MySQL root password: " DB_PASS
echo ""
read -p "Database name [spf_flattener]: " DB_NAME
DB_NAME=${DB_NAME:-spf_flattener}
echo ""

# Create database
echo "Creating database..."
mysql -u"$DB_USER" -p"$DB_PASS" -e "CREATE DATABASE IF NOT EXISTS $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

# Import schema
echo "Importing database schema..."
mysql -u"$DB_USER" -p"$DB_PASS" "$DB_NAME" < "$PROJECT_DIR/config/database.sql"

echo -e "${GREEN}✓ Database created successfully${NC}"
echo ""

# Update config file
echo "=== Configuration ==="
read -p "Application URL [http://localhost/spf-flattener]: " APP_URL
APP_URL=${APP_URL:-http://localhost/spf-flattener}

cat > "$PROJECT_DIR/config/config.local.php" << EOF
<?php
/**
 * Local Configuration Override
 * Generated by install.sh
 */

// Database configuration
define('DB_HOST', 'localhost');
define('DB_NAME', '$DB_NAME');
define('DB_USER', '$DB_USER');
define('DB_PASS', '$DB_PASS');
define('DB_CHARSET', 'utf8mb4');

// Application settings
define('APP_URL', '$APP_URL');

// Auto-update settings
define('AUTO_UPDATE_ENABLED', false); // Set to true to enable automatic updates

EOF

echo -e "${GREEN}✓ Configuration file created${NC}"
echo ""

# Set permissions
echo "=== Setting Permissions ==="
mkdir -p "$PROJECT_DIR/logs"
chmod 755 "$PROJECT_DIR/logs"
chmod 644 "$PROJECT_DIR/config/config.local.php"

echo -e "${GREEN}✓ Permissions set${NC}"
echo ""

# Cron job setup
echo "=== Cron Job Setup ==="
read -p "Set up automated cron job? (y/n): " SETUP_CRON

if [[ $SETUP_CRON =~ ^[Yy]$ ]]; then
    read -p "Check interval in minutes [60]: " CRON_INTERVAL
    CRON_INTERVAL=${CRON_INTERVAL:-60}
    
    CRON_JOB="*/$CRON_INTERVAL * * * * php $PROJECT_DIR/cron/auto-update.php --no-email >> $PROJECT_DIR/logs/cron.log 2>&1"
    
    (crontab -l 2>/dev/null | grep -v "auto-update.php"; echo "$CRON_JOB") | crontab -
    
    echo -e "${GREEN}✓ Cron job installed (runs every $CRON_INTERVAL minutes)${NC}"
    echo ""
    echo "Cron command: $CRON_JOB"
else
    echo "Skipping cron setup. You can manually add to crontab:"
    echo "  */60 * * * * php $PROJECT_DIR/cron/auto-update.php --no-email"
fi

echo ""
echo "======================================"
echo -e "${GREEN}  Installation Complete!${NC}"
echo "======================================"
echo ""
echo "Next steps:"
echo "1. Open $APP_URL in your browser"
echo "2. Configure your Cloudflare API credentials (optional)"
echo "3. Add your domains and approved senders"
echo "4. Click 'Flatten' to generate your SPF records"
echo ""
echo "For automatic updates:"
echo "  - Edit config/config.local.php and set AUTO_UPDATE_ENABLED to true"
echo "  - Configure your Cloudflare API credentials in the web interface"
echo ""
echo "Logs: $PROJECT_DIR/logs/"
echo ""
