#!/bin/bash
# ============================================================
#  ATS Solutions — SPF Flattener installer
#
#  1. Creates the MySQL database and tables
#  2. Writes config/config.local.php
#  3. Creates the first administrator account
#  4. Optionally installs the cron job
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'

echo ""
echo -e "${BLUE}==============================================${NC}"
echo -e "${BLUE}   ATS Solutions — SPF Flattener installer${NC}"
echo -e "${BLUE}==============================================${NC}"
echo ""

# ---- Preflight ------------------------------------------------
if ! command -v php >/dev/null 2>&1; then
    echo -e "${RED}Error: PHP is not installed.${NC}"; exit 1
fi
PHP_VERSION=$(php -r 'echo PHP_VERSION;')
echo -e "${GREEN}✓${NC} PHP ${PHP_VERSION}"

if ! php -m | grep -qi '^pdo_mysql$'; then
    echo -e "${RED}Error: the pdo_mysql extension is required.${NC}"; exit 1
fi
echo -e "${GREEN}✓${NC} pdo_mysql extension present"

if ! command -v mysql >/dev/null 2>&1; then
    echo -e "${RED}Error: the MySQL client is not installed.${NC}"; exit 1
fi
echo -e "${GREEN}✓${NC} MySQL client present"

if ! command -v dig >/dev/null 2>&1; then
    echo -e "${YELLOW}!${NC} 'dig' not found — DNS lookups will fail. Install dnsutils / bind-utils."
fi
echo ""

# ---- Database -------------------------------------------------
echo -e "${BLUE}Database configuration${NC}"
read -rp "MySQL host [localhost]: " DB_HOST;  DB_HOST=${DB_HOST:-localhost}
read -rp "MySQL user [root]: "       DB_USER;  DB_USER=${DB_USER:-root}
read -rsp "MySQL password: "         DB_PASS;  echo ""
read -rp "Database name [spf_flattener]: " DB_NAME; DB_NAME=${DB_NAME:-spf_flattener}
echo ""

MYSQL_ARGS=(-h"$DB_HOST" -u"$DB_USER")
[ -n "$DB_PASS" ] && MYSQL_ARGS+=(-p"$DB_PASS")

echo "Creating database…"
mysql "${MYSQL_ARGS[@]}" -e "CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

echo "Importing schema…"
mysql "${MYSQL_ARGS[@]}" "$DB_NAME" < "$SCRIPT_DIR/config/database.sql"

echo -e "${GREEN}✓${NC} Database ready"
echo ""

# ---- Local config --------------------------------------------
cat > "$SCRIPT_DIR/config/config.local.php" << EOF
<?php
/**
 * Local configuration — generated by install.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
 * Do not commit this file to version control.
 */

define('DB_HOST', '${DB_HOST}');
define('DB_NAME', '${DB_NAME}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');
define('DB_CHARSET', 'utf8mb4');

// Set this to the externally reachable base URL of the app.
define('APP_URL', 'http://${HOSTNAME}');

// Publish flattened records to Cloudflare automatically.
define('AUTO_UPDATE_ENABLED', false);
EOF

chmod 640 "$SCRIPT_DIR/config/config.local.php"
echo -e "${GREEN}✓${NC} Wrote config/config.local.php (mode 640)"
echo ""

# ---- Administrator account -----------------------------------
echo -e "${BLUE}Administrator account${NC}"
echo "The web interface requires a username and password."
read -rp "Admin username [admin]: " ADMIN_USER; ADMIN_USER=${ADMIN_USER:-admin}

echo "Creating account '${ADMIN_USER}' — you will be prompted for a password."
if ! php "$SCRIPT_DIR/cli.php" user:add --username="$ADMIN_USER" --role=admin --name="Administrator"; then
    echo -e "${RED}Failed to create the administrator account.${NC}"
    exit 1
fi
echo ""

# ---- Directories & permissions -------------------------------
mkdir -p "$SCRIPT_DIR/logs"
chmod 755 "$SCRIPT_DIR/logs"
echo -e "${GREEN}✓${NC} Log directory ready"
echo ""

# ---- Cron -----------------------------------------------------
echo -e "${BLUE}Scheduled flattening${NC}"
read -rp "Install the auto-update cron job? (y/N): " SETUP_CRON
if [[ "$SETUP_CRON" =~ ^[Yy]$ ]]; then
    read -rp "Interval in minutes [60]: " CRON_INTERVAL; CRON_INTERVAL=${CRON_INTERVAL:-60}
    CRON_JOB="*/${CRON_INTERVAL} * * * * php ${SCRIPT_DIR}/cron/auto-update.php --no-email >> ${SCRIPT_DIR}/logs/cron.log 2>&1"
    (crontab -l 2>/dev/null | grep -v 'auto-update.php'; echo "$CRON_JOB") | crontab -
    echo -e "${GREEN}✓${NC} Cron installed (every ${CRON_INTERVAL} min)"
else
    echo "Skipped. Add manually if needed:"
    echo "  */60 * * * * php ${SCRIPT_DIR}/cron/auto-update.php --no-email"
fi
echo ""

echo -e "${GREEN}==============================================${NC}"
echo -e "${GREEN}   Installation complete${NC}"
echo -e "${GREEN}==============================================${NC}"
echo ""
echo "Open the app in a browser and sign in with the account you just created."
echo ""
echo "Useful commands:"
echo "  php cli.php user:list"
echo "  php cli.php user:add   --username=name --role=operator"
echo "  php cli.php user:passwd --username=name"
echo "  php cli.php audit --id=50"
echo ""
